# Generated by Django 5.2.8 on 2025-11-08 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_dungeoncard_options_and_more'),
        ('users', '0002_userprofile_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='in_current_dungeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.dungeon'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_in_current_game',
            field=models.BooleanField(default=False),
        ),
    ]
