# Generated by Django 5.2.8 on 2025-11-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upgrade_points',
            field=models.IntegerField(default=0),
        ),
    ]
