# Generated by Django 5.2.8 on 2025-11-08 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('is_damage_doubled', models.BooleanField(default=False)),
                ('is_health_doubled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorldCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('base_damage', models.IntegerField()),
                ('base_health', models.IntegerField()),
                ('card_type', models.CharField(choices=[('fire', 'Tűz'), ('water', 'Víz'), ('earth', 'Föld'), ('air', 'Levegő')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dungeon_type', models.CharField(choices=[('simple', 'Egyszerű találkozás'), ('small', 'Kis kazamata'), ('large', 'Nagy kazamata')], max_length=10)),
                ('leader_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.leadercard')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_damage', models.IntegerField(default=0)),
                ('extra_health', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_stats', to=settings.AUTH_USER_MODEL)),
                ('world_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.worldcard')),
            ],
            options={
                'unique_together': {('player', 'world_card')},
            },
        ),
        migrations.CreateModel(
            name='PlayerCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to=settings.AUTH_USER_MODEL)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.dungeon')),
                ('player_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.playerdeck')),
            ],
        ),
        migrations.AddField(
            model_name='leadercard',
            name='base_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.worldcard'),
        ),
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('player_won', models.BooleanField()),
                ('reason', models.CharField(choices=[('damage', 'Sebzés'), ('type', 'Típus'), ('dungeon', 'Kazamata előny')], max_length=20)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cards.battle')),
                ('player_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.playercardstats')),
                ('dungeon_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.worldcard')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.playercardstats')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cards.playercollection')),
            ],
            options={
                'unique_together': {('collection', 'card_stats')},
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('card_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.playercardstats')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='cards.playerdeck')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('deck', 'order')},
            },
        ),
        migrations.CreateModel(
            name='DungeonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_cards', to='cards.dungeon')),
                ('world_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.worldcard')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('dungeon', 'order')},
            },
        ),
    ]
