# Generated by Django 5.2.8 on 2025-11-08 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerCardStats',
            new_name='PlayerCards',
        ),
        migrations.AlterUniqueTogether(
            name='collectionentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='collectionentry',
            name='card_stats',
        ),
        migrations.RemoveField(
            model_name='collectionentry',
            name='collection',
        ),
        migrations.AlterUniqueTogether(
            name='deckcard',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='deckcard',
            name='card_stats',
        ),
        migrations.RemoveField(
            model_name='deckcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='playercollection',
            name='player',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='won',
        ),
        migrations.DeleteModel(
            name='BattleLog',
        ),
        migrations.DeleteModel(
            name='CollectionEntry',
        ),
        migrations.DeleteModel(
            name='DeckCard',
        ),
        migrations.DeleteModel(
            name='PlayerCollection',
        ),
    ]
