# Generated by Django 5.2.8 on 2025-11-08 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_playercardstats_playercards_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dungeoncard',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dungeoncard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playerdeck',
            name='cards',
            field=models.ManyToManyField(to='cards.playercards'),
        ),
        migrations.CreateModel(
            name='DungeonDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cards', models.ManyToManyField(to='cards.dungeoncard')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='cards.dungeon')),
                ('leader_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.leadercard')),
            ],
        ),
        migrations.RemoveField(
            model_name='dungeoncard',
            name='order',
        ),
    ]
