# Generated by Django 5.2.8 on 2025-11-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_dungeoncard_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdeck',
            name='cards',
        ),
        migrations.AddField(
            model_name='playerdeck',
            name='card_ids',
            field=models.JSONField(default=list),
        ),
    ]
